---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# wcc

<!-- badges: start -->
<!-- badges: end -->

The goal of **wcc** is to provide a modern, high-efficiency R implementation of the windowed cross-correlation and peak picking algorithms

## Installation

You can install the development version of wcc from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jmgirard/wcc")
```

## Example

```{r example}
library(wcc)

data("sim_dyad")

# Step 1: Calculate 3D velocity for both individuals
sim_dyad$vel_A <- v_xyz(sim_dyad$time, sim_dyad$x_A, sim_dyad$y_A, sim_dyad$z_A)
sim_dyad$vel_B <- v_xyz(sim_dyad$time, sim_dyad$x_B, sim_dyad$y_B, sim_dyad$z_B)

# Step 2: Calculate Windowed Cross-Correlations
wcc_results <- wcc(
  x = sim_dyad$vel_A,
  y = sim_dyad$vel_B,
  window_size = 150,
  lag_max = 75,
  window_increment = 25,
  lag_increment = 1,
  na.rm = TRUE
)

# Step 3: Extract the Peaks
peaks <- pick_peaks(
  wcc_obj = wcc_results,
  L_size = 5,
  strict_monotonic = FALSE
)

# Step 4: Plot the landscape and overlay the shifting peaks
plot_peaks_overlay(wcc_results, peaks)
```
