// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pick_optima_cpp
DataFrame pick_optima_cpp(List metric_list, NumericVector i_vals, int tau_max, int L_size, bool strict_monotonic, bool find_min);
RcppExport SEXP _bsync_pick_optima_cpp(SEXP metric_listSEXP, SEXP i_valsSEXP, SEXP tau_maxSEXP, SEXP L_sizeSEXP, SEXP strict_monotonicSEXP, SEXP find_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type metric_list(metric_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type i_vals(i_valsSEXP);
    Rcpp::traits::input_parameter< int >::type tau_max(tau_maxSEXP);
    Rcpp::traits::input_parameter< int >::type L_size(L_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type strict_monotonic(strict_monotonicSEXP);
    Rcpp::traits::input_parameter< bool >::type find_min(find_minSEXP);
    rcpp_result_gen = Rcpp::wrap(pick_optima_cpp(metric_list, i_vals, tau_max, L_size, strict_monotonic, find_min));
    return rcpp_result_gen;
END_RCPP
}
// calc_wcc_cpp
NumericVector calc_wcc_cpp(NumericVector x, NumericVector y, IntegerVector i_vals, IntegerVector tau_vals, int w_max);
RcppExport SEXP _bsync_calc_wcc_cpp(SEXP xSEXP, SEXP ySEXP, SEXP i_valsSEXP, SEXP tau_valsSEXP, SEXP w_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i_vals(i_valsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tau_vals(tau_valsSEXP);
    Rcpp::traits::input_parameter< int >::type w_max(w_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_wcc_cpp(x, y, i_vals, tau_vals, w_max));
    return rcpp_result_gen;
END_RCPP
}
// calc_wdtw_cpp
NumericVector calc_wdtw_cpp(NumericVector x, NumericVector y, IntegerVector i_vals, IntegerVector tau_vals, int w_max, bool use_l2, bool local_scale);
RcppExport SEXP _bsync_calc_wdtw_cpp(SEXP xSEXP, SEXP ySEXP, SEXP i_valsSEXP, SEXP tau_valsSEXP, SEXP w_maxSEXP, SEXP use_l2SEXP, SEXP local_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i_vals(i_valsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tau_vals(tau_valsSEXP);
    Rcpp::traits::input_parameter< int >::type w_max(w_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type use_l2(use_l2SEXP);
    Rcpp::traits::input_parameter< bool >::type local_scale(local_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_wdtw_cpp(x, y, i_vals, tau_vals, w_max, use_l2, local_scale));
    return rcpp_result_gen;
END_RCPP
}
// calc_wgranger_cpp
DataFrame calc_wgranger_cpp(NumericVector x, NumericVector y, IntegerVector i_vals, int w_max, int p);
RcppExport SEXP _bsync_calc_wgranger_cpp(SEXP xSEXP, SEXP ySEXP, SEXP i_valsSEXP, SEXP w_maxSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i_vals(i_valsSEXP);
    Rcpp::traits::input_parameter< int >::type w_max(w_maxSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_wgranger_cpp(x, y, i_vals, w_max, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bsync_pick_optima_cpp", (DL_FUNC) &_bsync_pick_optima_cpp, 6},
    {"_bsync_calc_wcc_cpp", (DL_FUNC) &_bsync_calc_wcc_cpp, 5},
    {"_bsync_calc_wdtw_cpp", (DL_FUNC) &_bsync_calc_wdtw_cpp, 7},
    {"_bsync_calc_wgranger_cpp", (DL_FUNC) &_bsync_calc_wgranger_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_bsync(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
