# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pick_optima_cpp <- function(metric_list, i_vals, tau_max, L_size, strict_monotonic = FALSE, find_min = FALSE) {
    .Call(`_bsync_pick_optima_cpp`, metric_list, i_vals, tau_max, L_size, strict_monotonic, find_min)
}

calc_wcc_cpp <- function(x, y, i_vals, tau_vals, w_max) {
    .Call(`_bsync_calc_wcc_cpp`, x, y, i_vals, tau_vals, w_max)
}

calc_wdtw_cpp <- function(x, y, i_vals, tau_vals, w_max, use_l2, local_scale) {
    .Call(`_bsync_calc_wdtw_cpp`, x, y, i_vals, tau_vals, w_max, use_l2, local_scale)
}

calc_wgranger_cpp <- function(x, y, i_vals, w_max, p) {
    .Call(`_bsync_calc_wgranger_cpp`, x, y, i_vals, w_max, p)
}

